export const BIG = 2;
export const SMALL = 1;

export const TYPE_MAP = {
    1: '普通',
    2: '历战',
    3: '狂龙',
};

export const TYPE_COLOR_MAP = {
    1: 'success',
    2: 'primary',
    3: 'error',
};

export const PLACE_MAP = {
    1: '天堑沙原',
    2: '绯红森林',
    3: '涌油谷',
    4: '冰雾断崖',
    5: '龙都遗迹',
    6: '龙谷遗址',
};

export const PLACE_COLOR_MAP = {
    1: 'orange',
    2: 'green',
    3: 'red',
    4: 'cyan',
    5: 'geekblue',
    6: 'purple',
};

export const MONSTER_LIST = [
    {
        name: '缠蛙',
        pic: '/pic/1.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '炎尾龙',
        pic: '/pic/2.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '刺花蜘蛛',
        pic: '/pic/3.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '桃毛兽王',
        pic: '/pic/4.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '沙海龙',
        pic: '/pic/5.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '辟兽',
        pic: '/pic/6.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '波衣龙',
        pic: '/pic/7.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '沼喷龙',
        pic: '/pic/8.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '煌雷龙',
        pic: '/pic/9.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '影蜘蛛',
        pic: '/pic/10.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '风铗龙',
        pic: '/pic/11.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '赫猿兽',
        pic: '/pic/12.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '狱焰蛸',
        pic: '/pic/13.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '护辟兽',
        pic: '/pic/14.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '护火龙',
        pic: '/pic/15.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '冻峰龙',
        pic: '/pic/16.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: true,
    },
    {
        name: '护凶爪龙',
        pic: '/pic/17.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '暗器蛸',
        pic: '/pic/18.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '护锁刃龙',
        pic: '/pic/19.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: true,
    },
    {
        name: '白炽龙',
        pic: '/pic/20.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: true,
    },
    {
        name: '怪鸟',
        pic: '/pic/21.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '毒怪鸟',
        pic: '/pic/22.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '雌火龙',
        pic: '/pic/23.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '护雷颚龙',
        pic: '/pic/24.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '火龙',
        pic: '/pic/25.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '铠龙',
        pic: '/pic/26.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '雪狮子王',
        pic: '/pic/27.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '黑蚀龙',
        pic: '/pic/28.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    },
    {
        name: '锁刃龙',
        pic: '/pic/29.png',
        bigFlag: false,
        smallFlag: false,
        bigMissions: [],
        smallMissions: [],
        disabled: false,
    }
]
